if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    include(ClangCompilerOptions)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    include(GccCompilerOptions)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    include(MsvcCompilerOptions)
else()
    message(FATAL_ERROR "Unsupported compiler: ${CMAKE_CXX_COMPILER_ID}")
endif()
