name: CMake Ubuntu Build Matrix

on: [ workflow_dispatch ] # Trigger manually only

env:
  CMAKE_VERSION: 4.1.2

jobs:
  build:
    name: ${{ matrix.config.name }} - ${{ matrix.config.cmake_preset }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "MacOS with Clang Debug",
              os: macos-latest,
              cc: "clang", cxx: "clang++",
              cmake_preset: "clang-debug"
            }
          - {
              name: "MacOS with Clang Release",
              os: macos-latest,
              cc: "clang", cxx: "clang++",
              cmake_preset: "clang-release"
            }

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Download and update cmake to specified version
      id: install-cmake
      run: |
        cmake \
          -Dcmake_version="${{ env.CMAKE_VERSION }}" \
          -Drunner_os="${{ runner.os }}" \
          -P .github/scripts/install-cmake.cmake

    - name: Verion of cmake
      run: cmake --version

    - name: Create Build Directory
      run: mkdir -p ${{ github.workspace }}/build

    - name: List cmake presets
      run: cmake --list-presets

    - name: Run cmake
      run: |
        cmake \
          -Dcc="${{ matrix.config.cc }}" \
          -Dcxx="${{ matrix.config.cxx }}" \
          -Dcmake_preset="${{ matrix.config.cmake_preset }}" \
          -Drunner_os="${{ runner.os }}" \
          -P .github/scripts/configure-cmake.cmake

    - name: Build
      run: |
        cmake \
          -Dcmake_build_config="${{ matrix.config.cmake_build_config }}" \
          -P .github/scripts/build-cmake.cmake

    - name: Run tests
      run: |
        cmake \
          -Dctest_config="${{ matrix.config.ctest_config }}" \
          -P .github/scripts/test-cmake.cmake
